const GAME_DATA = {
    alphabet: [
        { letter: 'A', word: 'AVIÃO', emoji: '✈️' },
        { letter: 'B', word: 'BOLA', emoji: '⚽' },
        { letter: 'C', word: 'CASA', emoji: '🏠' },
        { letter: 'D', word: 'DADO', emoji: '🎲' },
        { letter: 'E', word: 'ELEFANTE', emoji: '🐘' },
        { letter: 'F', word: 'FOCA', emoji: '🦭' },
        { letter: 'G', word: 'GATO', emoji: '🐱' },
        { letter: 'H', word: 'HARPA', emoji: '🎶' },
        { letter: 'I', word: 'IGREJA', emoji: '⛪' },
        { letter: 'J', word: 'JACARÉ', emoji: '🐊' },
        { letter: 'K', word: 'KIWI', emoji: '🥝' },
        { letter: 'L', word: 'LÁPIS', emoji: '✏️' },
        { letter: 'M', word: 'MACACO', emoji: '🐵' },
        { letter: 'N', word: 'NUVEM', emoji: '☁️' },
        { letter: 'O', word: 'OVO', emoji: '🥚' },
        { letter: 'P', word: 'PATO', emoji: '🦆' },
        { letter: 'Q', word: 'QUEIJO', emoji: '🧀' },
        { letter: 'R', word: 'RATO', emoji: '🐭' },
        { letter: 'S', word: 'SOL', emoji: '☀️' },
        { letter: 'T', word: 'TREM', emoji: '🚂' },
        { letter: 'U', word: 'UVA', emoji: '🍇' },
        { letter: 'V', word: 'VACA', emoji: '🐮' },
        { letter: 'W', word: 'WIFI', emoji: '📶' },
        { letter: 'X', word: 'XÍCARA', emoji: '☕' },
        { letter: 'Y', word: 'YOGA', emoji: '🧘' },
        { letter: 'Z', word: 'ZEBRA', emoji: '🦓' },
        { letter: 'A', word: 'ABACAXI', emoji: '🍍' },
        { letter: 'B', word: 'BONECA', emoji: '👧' },
        { letter: 'C', word: 'CACHORRO', emoji: '🐶' },
        { letter: 'D', word: 'DEDO', emoji: '👆' },
        { letter: 'E', word: 'ESCADAS', emoji: '🪜' },
        { letter: 'F', word: 'FLOR', emoji: '🌸' },
        { letter: 'G', word: 'GIRAFA', emoji: '🦒' },
        { letter: 'H', word: 'HOMEM', emoji: '👨' },
        { letter: 'I', word: 'ILHA', emoji: '🏝️' },
        { letter: 'J', word: 'JANELA', emoji: '🖼️' },
        { letter: 'L', word: 'LIVRO', emoji: '📖' },
        { letter: 'M', word: 'MALA', emoji: '💼' },
        { letter: 'N', word: 'NINHO', emoji: '🪺' },
        { letter: 'O', word: 'ÓCULOS', emoji: '👓' },
        { letter: 'P', word: 'PIPA', emoji: '🪁' },
        { letter: 'Q', word: 'QUADRO', emoji: '🖼️' },
        { letter: 'R', word: 'ROSA', emoji: '🌹' },
        { letter: 'S', word: 'SINO', emoji: '🔔' },
        { letter: 'T', word: 'TARTARUGA', emoji: '🐢' },
        { letter: 'U', word: 'URSO', emoji: '🐻' },
        { letter: 'V', word: 'VIOLÃO', emoji: '🎸' },
        { letter: 'Z', word: 'ZÍPER', emoji: '🪡' }
    ],
    syllables: [
        { syllable: 'BA', word: 'BALA', emoji: '🍬' },
        { syllable: 'BE', word: 'BEBÊ', emoji: '👶' },
        { syllable: 'BI', word: 'BICO', emoji: '🦆' },
        { syllable: 'BO', word: 'BOLO', emoji: '🎂' },
        { syllable: 'BU', word: 'BÚFALO', emoji: '🦬' },
        { syllable: 'CA', word: 'CASA', emoji: '🏠' },
        { syllable: 'CE', word: 'CENOURA', emoji: '🥕' },
        { syllable: 'CI', word: 'CIDADE', emoji: '🏙️' },
        { syllable: 'CO', word: 'COPO', emoji: '🥤' },
        { syllable: 'CU', word: 'CUBO', emoji: '🧊' },
        { syllable: 'DA', word: 'DADO', emoji: '🎲' },
        { syllable: 'DE', word: 'DEDO', emoji: '👆' },
        { syllable: 'DI', word: 'DIA', emoji: '☀️' },
        { syllable: 'DO', word: 'DOCE', emoji: '🍭' },
        { syllable: 'DU', word: 'DUAS', emoji: '2️⃣' },
        { syllable: 'FA', word: 'FADA', emoji: '🧚' },
        { syllable: 'FE', word: 'FEIJÃO', emoji: '🫘' },
        { syllable: 'FI', word: 'FITA', emoji: '🎀' },
        { syllable: 'FO', word: 'FOGUETE', emoji: '🚀' },
        { syllable: 'FU', word: 'FUMAÇA', emoji: '💨' },
        { syllable: 'GA', word: 'GATO', emoji: '🐱' },
        { syllable: 'GE', word: 'GELO', emoji: '🧊' },
        { syllable: 'GI', word: 'GIRAFA', emoji: '🦒' },
        { syllable: 'GO', word: 'GOTA', emoji: '💧' },
        { syllable: 'GU', word: 'GURI', emoji: '👦' },
        { syllable: 'JA', word: 'JACA', emoji: '🍈' },
        { syllable: 'JE', word: 'JEEP', emoji: '🚙' },
        { syllable: 'JI', word: 'JIBOIA', emoji: '🐍' },
        { syllable: 'JO', word: 'JOANINHA', emoji: '🐞' },
        { syllable: 'JU', word: 'JUJUBAS', emoji: '🍬' },
        { syllable: 'LA', word: 'LÁPIS', emoji: '✏️' },
        { syllable: 'LE', word: 'LEÃO', emoji: '🦁' },
        { syllable: 'LI', word: 'LIXO', emoji: '🗑️' },
        { syllable: 'LO', word: 'LOBO', emoji: '🐺' },
        { syllable: 'LU', word: 'LUA', emoji: '🌙' },
        { syllable: 'MA', word: 'MACACO', emoji: '🐵' },
        { syllable: 'ME', word: 'CADEIRA', emoji: '🪑' },
        { syllable: 'MI', word: 'MILHO', emoji: '🌽' },
        { syllable: 'MO', word: 'MOTO', emoji: '🏍️' },
        { syllable: 'MU', word: 'MURALHA', emoji: '🧱' },
        { syllable: 'NA', word: 'NAVIO', emoji: '🚢' },
        { syllable: 'NE', word: 'NEVE', emoji: '❄️' },
        { syllable: 'NI', word: 'NINHO', emoji: '🪺' },
        { syllable: 'NO', word: 'NOITE', emoji: '🌃' },
        { syllable: 'NU', word: 'NUVEM', emoji: '☁️' },
        { syllable: 'PA', word: 'PATO', emoji: '🦆' },
        { syllable: 'PE', word: 'PEIXE', emoji: '🐟' },
        { syllable: 'PI', word: 'PIPA', emoji: '🪁' },
        { syllable: 'PO', word: 'PORCO', emoji: '🐷' },
        { syllable: 'PU', word: 'PUDIM', emoji: '🍮' },
        { syllable: 'RA', word: 'RATO', emoji: '🐭' },
        { syllable: 'RE', word: 'REDE', emoji: '🥅' },
        { syllable: 'RI', word: 'RIO', emoji: '🏞️' },
        { syllable: 'RO', word: 'ROBÔ', emoji: '🤖' },
        { syllable: 'RU', word: 'RUA', emoji: '🛣️' },
        { syllable: 'SA', word: 'SAPO', emoji: '🐸' },
        { syllable: 'SE', word: 'SELO', emoji: '✉️' },
        { syllable: 'SI', word: 'SINO', emoji: '🔔' },
        { syllable: 'SO', word: 'SOL', emoji: '☀️' },
        { syllable: 'SU', word: 'SUCO', emoji: '🧃' },
        { syllable: 'TA', word: 'TATU', emoji: '🦔' },
        { syllable: 'TE', word: 'TELEFONE', emoji: '📞' },
        { syllable: 'TI', word: 'TIGRE', emoji: '🐯' },
        { syllable: 'TO', word: 'TOMATE', emoji: '🍅' },
        { syllable: 'TU', word: 'TURMA', emoji: '🧑‍🤝‍🧑' },
        { syllable: 'VA', word: 'VACA', emoji: '🐮' },
        { syllable: 'VE', word: 'VELA', emoji: '🕯️' },
        { syllable: 'VI', word: 'VIOLÃO', emoji: '🎸' },
        { syllable: 'VO', word: 'VOVÓ', emoji: '👵' },
        { syllable: 'VU', word: 'VULCÃO', emoji: '🌋' },
        { syllable: 'ZA', word: 'ZANGÃO', emoji: '🐝' },
        { syllable: 'ZE', word: 'ZEBRA', emoji: '🦓' },
        { syllable: 'ZI', word: 'ZÍPER', emoji: '🪡' },
        { syllable: 'ZO', word: 'ZOOLÓGICO', emoji: '🦁' },

    ],
    words: [
        { word: 'BOLA', syllables: ['BO', 'LA'], emoji: '⚽', hint: 'Usamos para jogar' },
        { word: 'CASA', syllables: ['CA', 'SA'], emoji: '🏠', hint: 'Onde moramos' },
        { word: 'GATO', syllables: ['GA', 'TO'], emoji: '🐱', hint: 'Animal que faz miau' },
        { word: 'PATO', syllables: ['PA', 'TO'], emoji: '🦆', hint: 'Ave que nada' },
        { word: 'RATO', syllables: ['RA', 'TO'], emoji: '🐭', hint: 'Pequeno roedor' },
        { word: 'SAPO', syllables: ['SA', 'PO'], emoji: '🐸', hint: 'Animal que pula' },
        { word: 'VACA', syllables: ['VA', 'CA'], emoji: '🐮', hint: 'Dá leite' },
        { word: 'LUA', syllables: ['LU', 'A'], emoji: '🌙', hint: 'Brilha no céu à noite' },
        { word: 'SOL', syllables: ['SOL'], emoji: '☀️', hint: 'Brilha no céu de dia' },
        { word: 'BOLO', syllables: ['BO', 'LO'], emoji: '🎂', hint: 'Comemos em aniversários' },
        { word: 'LIVRO', syllables: ['LI', 'VRO'], emoji: '📖', hint: 'Usamos para ler' },
        { word: 'CADEIRA', syllables: ['CA', 'DEI', 'RA'], emoji: '🪑', hint: 'Onde sentamos' },
        { word: 'FOGUETE', syllables: ['FO', 'GUE', 'TE'], emoji: '🚀', hint: 'Viaja para o espaço' },
        { word: 'PEIXE', syllables: ['PE', 'IXE'], emoji: '🐟', hint: 'Nada na água' },
        { word: 'FLOR', syllables: ['FLOR'], emoji: '🌸', hint: 'Cheirosa e bonita' },
        { word: 'JANELA', syllables: ['JA', 'NE', 'LA'], emoji: '🖼️', hint: 'Abrimos para ver lá fora' },
        { word: 'MOTO', syllables: ['MO', 'TO'], emoji: '🏍️', hint: 'Veículo de duas rodas' },
        { word: 'NUVEM', syllables: ['NU', 'VEM'], emoji: '☁️', hint: 'Flutua no céu' },
        { word: 'PIPA', syllables: ['PI', 'PA'], emoji: '🪁', hint: 'Voa com o vento' },
        { word: 'ROBÔ', syllables: ['RO', 'BÔ'], emoji: '🤖', hint: 'Máquina que ajuda' },
        { word: 'SINO', syllables: ['SI', 'NO'], emoji: '🔔', hint: 'Faz barulho na igreja' },
        { word: 'TREM', syllables: ['TREM'], emoji: '🚂', hint: 'Anda sobre trilhos' },
        { word: 'UVA', syllables: ['U', 'VA'], emoji: '🍇', hint: 'Fruta pequena e roxa' },
        { word: 'ZEBRA', syllables: ['ZE', 'BRA'], emoji: '🦓', hint: 'Cavalo listrado' },
        { word: 'CENOURA', syllables: ['CE', 'NOU', 'RA'], emoji: '🥕', hint: 'Coelho adora comer' },
        { word: 'DEDO', syllables: ['DE', 'DO'], emoji: '👆', hint: 'Parte da mão' },
        { word: 'FITA', syllables: ['FI', 'TA'], emoji: '🎀', hint: 'Para amarrar ou decorar' },
        { word: 'MILHO', syllables: ['MI', 'LHO'], emoji: '🌽', hint: 'Amarelo, vira pipoca' },
        { word: 'NAVIO', syllables: ['NA', 'VIO'], emoji: '🚢', hint: 'Grande barco' },
        { word: 'PORCO', syllables: ['POR', 'CO'], emoji: '🐷', hint: 'Animal rosa que faz "óinc"' },
        { word: 'TOMATE', syllables: ['TO', 'MA', 'TE'], emoji: '🍅', hint: 'Fruta vermelha, parece legume' }
    ],
    vowels: ['A', 'E', 'I', 'O', 'U']
};